### ISSUE TITLE
Press duration example not working - Previous Duration and Current Duration methods always return zero

### ISSUE THREAD

**Issue by Redwoodstudio** [Leafwing-Studios/leafwing-input-manager#127]
## Version

0.3.0
Bevy 0.7.0

## Operating system & version
Windows 10

## What you did

I tried running the _press_duration_ example.
## What you expected to happen

From my understating, the player object should "leap" when the left/right key is released, with the leap distance dependent on the length of the keypress.

## What actually happened

The player object didn't move at all.

## Additional information

I've narrowed down the problem to the _previous_duration_ and the _current_duration_ functions always returning zero. 

A minimal example of the issue (edited _minimal_ example)
```
use bevy::prelude::*;
use leafwing_input_manager::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(InputManagerPlugin::<Action>::default())
        .add_startup_system(spawn_player)
        .add_system(jump)
        .run();
}

#[derive(Actionlike, PartialEq, Eq, Clone, Copy, Hash, Debug)]
enum Action {
    Run,
    Jump,
}

#[derive(Component)]
struct Player;

fn spawn_player(mut commands: Commands) {
    commands
        .spawn()
        .insert(Player)
        .insert_bundle(InputManagerBundle::<Action> {
            action_state: ActionState::default(),
            input_map: InputMap::new([(Action::Jump, KeyCode::Space)]),
        });
}
fn jump(query: Query<&ActionState<Action>, With<Player>>) {
    let action_state = query.single();
    if action_state.just_released(Action::Jump) {
        info!("End jump time: {:?}", action_state.previous_duration(Action::Jump));
    }
    if action_state.pressed(Action::Jump) {
        info!("Current jump time: {:?}", action_state.current_duration(Action::Jump));
    }
    if action_state.just_pressed(Action::Jump) {
        info!("Started jump!");
    }
}
```

**Comment by alice-i-cecile** [comment]
Thanks for the report. I'll take a look! Tests are passing, so something funky must be going on...

**Comment by krojew** [comment]
Can confirm - they are always 0.

**Comment by alice-i-cecile** [comment]
Examining this today :)

**Comment by alice-i-cecile** [comment]
This is a bug in the library, not the example. Going to fix and release ASAP.

**Comment by alice-i-cecile** [comment]
This was so, so much harder to fix than I expected. Sorry about the wait!

**Comment by Redwoodstudio** [comment]
Awesome, thank you so much!
