### ISSUE TITLE
DPad Buttons Presses Not Detected

### ISSUE THREAD

**Issue by zicklag** [Leafwing-Studios/leafwing-input-manager#149]
## Version

Version 0.3.0

## Operating system & version

Pop!_OS ( Ubuntu ) 20.04

## What you did

I took the `minimal` example in this repo and set the jump action to be bound like this:

```rust
input_map: InputMap::new([(Action::Jump, GamepadButtonType::DPadUp)])
                .set_gamepad(Gamepad(0))
                .build()
```

I also had to add the `bevy_gilrs` feature to the list of Bevy features in the `Cargo.toml`.

## What you expected to happen

Pressing up on the dpad should print "I'm jumping"

## What actually happened

Nothing.

## Additional information

This does work with non-dpad controller buttons.

I'm still investigating, but it looks like Bevy handles the dpad as an axis type, not as a button type, so the "pressed" detection doesn't work for the dpad like it is expected to in the current code.

Also, I would be interesting in adding basic support for triggering user actions based on analog sticks anyway, because I'm wanting that for my game. I'm assuming you'd be open to a PR? :)

I think the implementation direction for fixing this is probably just about the same for supporting analog sticks, because Bevy treats the dpad almost the same or exactly the same as the analog sticks.

**Comment by alice-i-cecile** [comment]
> I'm still investigating, but it looks like Bevy handles the dpad as an axis type, not as a button type, so the "pressed" detection doesn't work for the dpad like it is expected to in the current code.

I *think* is that this is an oddity in `gilrs`. I remember this behaving differently for users based on what hardware is used :(

> Also, I would be interesting in adding basic support for triggering user actions based on analog sticks anyway, because I'm wanting that for my game. I'm assuming you'd be open to a PR? :)

Yes please! See #78 for initial thoughts.

**Comment by zicklag** [comment]
> I think is that this is an oddity in gilrs. I remember this behaving differently for users based on what hardware is used :(

I was able to trace this to `bevy_gilrs` disabling one of the default `gilrs` event filters that is used to convert dpad axes events into dpad button events. I'll make a PR to bevy to update that, which should close this issue, but I'll still look into getting axis support in `leafwing-input-manager` so that we can use analog sticks, too.

**Comment by zicklag** [comment]
Since this is verified as a Bevy issue I think it's reasonable to close this now. I opened a PR that should fix on the Bevy side: https://github.com/bevyengine/bevy/pull/5220.
