### ISSUE TITLE
Why is Rotation measured "clockwise from midnight"?

### ISSUE THREAD

**Issue by CleanCut** [Leafwing-Studios/leafwing-input-manager#155]
@alice-i-cecile While experimenting with #151 I noticed that Rotation is measured "clockwise from midnight". Is this an intentional decision? Does it need to be this way?

It would be much more convenient to interact with standard `f32` math as well as things like `rapier2d` if Rotation were measured _counter-clockwise from the positive X axis_ (or "counter-clockwise from 3 o'clock" to put it in the same terms). 

Currently, any angle returned by `Rotation::to_radians` needs some extra calculations to get the radians value you need for any standard `f32` math. For example, I'm trying to determine the angle that a player is attempting to fly in 2D space via the axis returned by a gampad stick. Right now, after I get a value from the input manager, I've got to flip the rotation and shift the rotation origin.

From looking over the implementation of Rotation, it _seems_ like switching to the same measurement system as the rest of mathematics would be fairly straightforward. For example, the order of the first two arguments in [this line](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/9a07bb13f7d77cf6efa4bf78a64d87a6aac1af53/src/orientation.rs#L331) would go back to the standard y first and then x, and we could stop [flipping the sign](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/9a07bb13f7d77cf6efa4bf78a64d87a6aac1af53/src/orientation.rs#L686) in some places to restore the counter-clockwise rotation, and use the [unit X vector instead of the unit Y vector](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/9a07bb13f7d77cf6efa4bf78a64d87a6aac1af53/src/orientation.rs#L692) to measure from the positive X axis.

Is this a change you would be open to? I don't want to make a PR to change this if it needs to be kept this way for some reason I don't know.

**Comment by alice-i-cecile** [comment]
This was totally arbitrary. I tend to find it a bit easier to reason about, but have no strong feelings.

I would accept that PR if you made it; the interop argument is reasonable.
