### ISSUE TITLE
Instead of "pressed", use the term "activated"?

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#157]
@alice-i-cecile Instead of "pressed", would it be clearer to (someday) use the term "active" or "activated"? This returns `true` for an axis if it is outside of the deadzone.

_Originally posted by @CleanCut in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/151#discussion_r917113773_

This helps us move beyond the initial button-only design in a clearer fashion.

**Comment by alice-i-cecile** [comment]
Talking about this with @plof27. Her opinion is that we should keep this because:

1. Consistency with bevy_input is important.
2. This is a high churn change for little user benefit.
3. Actions are still modelled as virtual buttons (with metadata) and this terminology accurately communicates this design to users.

**Comment by plof27** [comment]
Thanks for typing that for me >.>

**Comment by CleanCut** [comment]
Alrighty 👍🏻
