### ISSUE TITLE
macros crate name v macros dependency

### ISSUE THREAD

**Issue by shnewto** [Leafwing-Studios/leafwing-input-manager#160]
## Version

9a07bb13f7d77cf6efa4bf78a64d87a6aac1af53

## Operating system & version

macOs 12.4

## What you did

```
cargo build
```
(I was actually trying to run examples but it's easy to reproduce with just `cargo build`)

## What you expected to happen

a successful build 😄 

What you think should've happened if everything was working properly.

a successful build 😄 

## What actually happened

```
> $ cargo build                                                                                   ⬡ system [±main ✓]
error: no matching package found
searched package name: `leafwing_input_manager_macros`
perhaps you meant:      leafwing-input-manager-macros
location searched: /Users/user/workspace/leafwing-input-manager/macros
required by package `leafwing-input-manager v0.4.0 (/Users/user/leafwing-input-manager)`
```

## Additional information

Hello! 👋 

I could definitely be doing something wrong this morning 😅 But it looks like this was missed in the last commit on master. I'm raising this as an issue instead of a PR because it looks like dev is using `_` and I'm not exactly sure what the flow is for bugs on `main` vs things that should be in PR'd to `dev`. 

Thanks!

**Comment by alice-i-cecile** [comment]
Oh no, did I break this... I hate cargo's poor handling of `-` and the inability to rename crates to fix that.

Can you please submit a PR to main? I'll do a very small minor version bump ASAP.

**Comment by shnewto** [comment]
sure thing!

**Comment by shnewto** [comment]
@alice-i-cecile made PR #161 but it doesn't seem to let me request you as a reviewer so I'll request here 😄

**Comment by alice-i-cecile** [comment]
Fixed by #161.

**Comment by alice-i-cecile** [comment]
@shnewto what exactly are you using for your build process? This was working successfully for me both locally and in CI.

**Comment by shnewto** [comment]
I'll try and retrace my steps.
- cloned leafwing-input-manager repo
- `cargo build`
- received the error output in the description above
- noticed the last commit on master 9a07bb13f7d77cf6efa4bf78a64d87a6aac1af53  (just _after_ the 0.4.0 release) changed the name of the macros crate to `leafwing-input-manager-macros`
- saw that the top level Cargo.toml was still looking for `leafwing_input_manager_macros` instead of the new hyphenated name
- locally, I changed the top level Cargo.toml dependency to use the hyphenated name and it built happily so I raised the the issue 

Where things wen't wrong I think is that my fix assumed that the macros crate should have the hyphens but maybe that crate's name should go back to underscores in the post 0.4.0 code here?

**Comment by alice-i-cecile** [comment]
Minor version published, thanks a ton @shnewto :)
