### ISSUE TITLE
Create a gamepad registration example

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#18]
Use a Nintendo Switch style "press L and R" to register prompt.

**Comment by 100-TomatoJuice** [comment]
I would be interested in creating this example, but I have a question. How do I know what gamepad uses the `Action` to join? Before, I had a work-around where I used `EventReader<GamepadButtonChangedEvent>` to get the first gamepad when the `Action` is pressed. Then, I stored the gamepad in a resource so a player can't join with the same gamepad over and over again. 
```rust
#[derive(Default, Resource)]
pub struct UsedGamepads{
    gamepads: HashMap<Gamepad, Entity>,
}
```

It worked fine, but has the limitation of only allowing one gamepad to join every frame. So, if two players pressed to join at once, only one would join. This becomes more of an issue at lower framerates. Although, I think this just inherit as `Action` only has `.pressed()` and doesn't know how many inputs are pressing it.

Something like #308 would make this cleaner, but there is some concerns with it as you noted in the comments. If you'd like, I can make the example with the method I described above, hold off for adding that data the action somehow, or try a 3rd way.

**Comment by alice-i-cecile** [comment]
It's still useful / important as an LWIM example: we need to show how to set the associated gamepad for multiple player entitles correctly :)

**Comment by 100-TomatoJuice** [comment]
>  we need to show how to set the associated gamepad for multiple player entitles correctly

That's true. I can get started tomorrow on making the example. For "L+R to join" to work with this example in the future, would Bevy input itself have to support chords?

**Comment by alice-i-cecile** [comment]
Hmm. It would be nicer, but detecting that simple of a chord in a one-off way would be fine to manually write out.
