### ISSUE TITLE
Re-enable bevy_egui input_binding example and update dependency

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#181]
Blocked on https://github.com/mvlabat/bevy_egui/pull/111.

**Comment by DGriffin91** [comment]
@alice-i-cecile What to see if the latest update of this PR is working for you?

**Comment by alice-i-cecile** [comment]
@DGriffin91 Our needs are super simple here; if you've got it compiling on your end I'm happy to trust that data until there's a full `bevy_egui` release :)

**Comment by zicklag** [comment]
This was done in #192 :heart:
