### ISSUE TITLE
Input Disable or Pause Feature

### ISSUE THREAD

**Issue by zicklag** [Leafwing-Studios/leafwing-input-manager#182]
## What problem does this solve?

I have a controller input binding menu and while I'm waiting for input for the binding, I wan to disable any `MenuAction` responses through leafwing.

## What solution would you like?

I was thinking we might be able to have a `enable()` and `disable()` functions on the `ActionState` that would allow you to block all input processing to it

## [Optional] How could this be implemented?

Probably just adding a flag to `ActionState` and functions to toggle it

## [Optional] What alternatives have you considered?

I'm currently able to manually consume inputs I know will cause trouble. For instance, while waiting for controller bindings, I consume the `MenuInput::Confirm` action that if not consumed will cause you to immediately re-click the button to start the binding process, if you happen to want to bind the select button to a game action.

## Related work

None.

**Comment by alice-i-cecile** [comment]
Can you use the `ToggleActions<A>` resource? https://github.com/Leafwing-Studios/leafwing-input-manager/blob/c6a1e9736fd7aec3a62e9abc3edfc6a25c1d75d8/src/systems.rs#L193

That was added for pretty much exactly this pattern :)

**Comment by zicklag** [comment]
Yep, that works. I didn't see that, thanks!
