### ISSUE TITLE
Support mouse delta input

### ISSUE THREAD

**Issue by hankjordan** [Leafwing-Studios/leafwing-input-manager#184]
Mouse delta is often used when building an FPS style game, for rotating the player camera.

Typically, the mouse locks to the screen and you would be able to move it up to look up, left to look left, etc.

Ideally this should be implemented in such a way that the developer does not have to discriminate between a controller and a mouse when creating their `apply_input` systems.

**Comment by alice-i-cecile** [comment]
Added in #186.
