### ISSUE TITLE
After ActionState::press sometimes becomes unset

### ISSUE THREAD

**Issue by Shatur** [Leafwing-Studios/leafwing-input-manager#191]
## Version

c6a1e9736fd7aec3a62e9abc3edfc6a25c1d75d8 (current master)

## Operating system & version

ArchLinux

## What you did

1. Apply this patch (`git apply <path>`): [bug.txt](https://github.com/Leafwing-Studios/leafwing-input-manager/files/9222133/bug.txt)
2. `cargo run --example minimal`
3. Press `W`.

## What you expected to happen

The following output:

```
I'm running!
I'm jumping!
```

## What actually happened

```
I'm running!
```

## Additional information

It looks like the bug occurs only if I use https://github.com/IyesGames/iyes_loopless. I'm not sure if it's a bug in `iyes_loopless` or it triggers some edge case in this plugin :)

**Comment by alice-i-cecile** [comment]
I wonder if it's related to https://github.com/Leafwing-Studios/leafwing-input-manager/issues/127, which has since been fixed. I'm going to punt on this until after Bevy 0.8 is out and you can try another reproduction with the new versions of everything.

**Comment by alice-i-cecile** [comment]
@Shatur now that there's a release, let me know if you can get a reproduction and link me to a branch :)

**Comment by Shatur** [comment]
Yes, the bug still exists, here is the updated patch for the latest master:
[bug.txt](https://github.com/Leafwing-Studios/leafwing-input-manager/files/9245863/bug.txt)
