### ISSUE TITLE
Split `MockingInput` trait 

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/leafwing-input-manager#195]
## Which code could be improved?

The `MockingInput` trait contains three things:

1. methods that send input and receive input
2. methods that test if something is pressed
3. methods that are related to `bevy_ui` 

## How should this be changed?

These three groups should be split into separate traits.

**Comment by alice-i-cecile** [comment]
We can implement #2 for `InputStreams`, allowing us to refactor the code further.
