### ISSUE TITLE
Modifier key inputs that are agnostic to which modifier key was pressed

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#211]
## What problem does this solve?

Bind an action to `Shift  + A`, in a way that doesn't care about which input was pressed.

## What solution would you like?

Have an alternative to `KeyCode` for modifier keys (Ctrl/Alt etc) where we don't care about whether we're hitting the left or right modifier (this is the most common case by far).

**Comment by Pulau-Komodo** [comment]
What should happen if someone activates `LShift` and `A`, then activates `RShift`, then releases `LShift`?

**Comment by alice-i-cecile** [comment]
Hmm. I think it should continue to detect the action as pressed the entire time.
