### ISSUE TITLE
Nintendo pro controller not detected/used unless using in Steam first

### ISSUE THREAD

**Issue by ericvrp** [Leafwing-Studios/leafwing-input-manager#226]
## Version

0.5.1

## Operating system & version

macOs latest (Apple Silicon)

## What you did

`SingleAxis::symmetric(GamepadAxisType::LeftStickY, 0.1)` and  `GamepadButtonType::LeftTrigger` do not trigger even though the logs show `2022-08-05T22:05:28.846521Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected`
It does work after I have used the controller in Steam. However in that case Leafwing seems to trigger at random.

## What you expected to happen

I expect LeftStickY & LeftTrigger to work out of the box 

## What actually happened

Random events/button pressed seem to be fired

## Additional information

Tested with an usb-c cable and over bluetooth but no difference.

**Comment by alice-i-cecile** [comment]
Interesting 🤔 Can you reproduce with just Bevy? I suspect this is actually a bug that needs to be fixed with https://gitlab.com/gilrs-project/gilrs

**Comment by ericvrp** [comment]
I could reproduce with just the demo on https://gitlab.com/gilrs-project/gilrs (without Bevy) and it seems to be specific to the Nintendo Pro Controller.  An old usb NES controller worked 100% fine.
