### ISSUE TITLE
Support input/device groups

### ISSUE THREAD

**Issue by sphinxc0re** [Leafwing-Studios/leafwing-input-manager#238]
## What problem does this solve?

Most video games that support multiple input methods need to show button prompts at some point. To find out which set of images need to be shown for a specific set of inputs, there has to be a way to check which "input group" is currently active e.g. controller or keyboard and mouse.

## What solution would you like?

I would like to be able to group input maps in to input groups with either names or typed labels. I then want those groups be attached to the ActionState so it is easily retrievable.

EDIT: There is a great video that explains what I want to achieve with this feature: https://youtu.be/watch?v=d6GtGbI-now

**Comment by sphinxc0re** [comment]
Is there any chance for this to be on the roadmap at some point? 🙏🏼

**Comment by alice-i-cecile** [comment]
Definitely on board with this, but I'm generally busy with Bevy itself. If you'd like to try your hand at a PR or design for this I'd be happy to help review and give design feedback.

**Comment by alice-i-cecile** [comment]
#242 is the same idea; closing in favor of that.
