### ISSUE TITLE
Add controller connected/disconnected event

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-input-manager#243]
## What problem does this solve?

- As a player, I want the game to be paused when I disconnect my controller.
- As a developer, I want an easy connect/disconnect event that I can react to.

## What solution would you like?

A new event enum with two values, `Connected` and `Disconnected`, that are emitted when I connect or disconnect a controller to/from my device.

Then I can build a system to react to these events, e.g. pausing my game when a controller has been disconnected.

## Related work

- Pausing the game on controller disconnect is part of the [Steamworks Input guidelines](https://partner.steamgames.com/doc/features/steam_controller/getting_started_for_devs#5).

**Comment by alice-i-cecile** [comment]
bevy_input already provides a raw version of this; IMO this should be done upstream :)
