### ISSUE TITLE
ActionState action is never released if InputMap is removed while input is held

### ISSUE THREAD

**Issue by paul-hansen** [Leafwing-Studios/leafwing-input-manager#244]
## Version

bevy = "0.8.0"
leafwing-input-manager = "0.5.2"

## Operating system & version

Windows 11 & Wasm

## What you did

I removed an InputMap from an entity (e.g. it was captured an taken over by an AI.) while pressing a button.

## What you expected to happen

When I remove the input map, the related ActionState would no longer report the buttons from that InputMap as being pressed.

## What actually happened

The ActionState continued say the action was being pressed after the InputMap was removed.

## Additional information

You can see this happening in the 0.3.0 release of my bevy jam 2 game: https://github.com/paul-hansen/bevy-jam-2/releases/tag/v0.3.0
If you are captured while you are boosting (press spacebar) your entity will keep boosting forever even though it should only be boosting if its new leader is boosting.

To work around this, I'm now adding this line during `CoreStage::Last` to clear the inputs from that frame (idk if this will have undesired side effects?)
``` rust
action_state.set_action_data(Actions::Boost, ActionData::default());
```

**Comment by paul-hansen** [comment]
I'd be happy to work on a PR for this after the jam is over. If you have any info on what you think the desired fix should be let me know. 

Also, I run into the same problem of inputs not resetting when I set the action's data manually using `set_action_data`, though that was a bit more expected. It isn't clear if that's an appropriate way to send inputs for AI or not, but that's related to https://github.com/Leafwing-Studios/leafwing-input-manager/issues/70 .

**Comment by paul-hansen** [comment]
A naïve solution might be to just reset all of the action data when an InputMap is removed from an entity, but I'm not sure if that might cause missed inputs or something. Perhaps iterate over the inputs from the InputMap and unapply them when the input map is removed would be a more careful solution?
 
If there isn't a good way to handle this, maybe we should just document that if InputMap is removed the action data is not cleared and will need to be cleared manually if being taken over by an AI or perhaps another InputMap. Could include an example of a system that does this.

Also I wasn't sure if this should be considered a bug or not, feel free to re-label this as usability or whatever.

**Comment by alice-i-cecile** [comment]
> A naïve solution might be to just reset all of the action data when an InputMap is removed from an entity, but I'm not sure if that might cause missed inputs or something

This would be my initial approach here :)
