### ISSUE TITLE
Adding inversion to mouse and gamepad axes

### ISSUE THREAD

**Issue by Kamduis** [Leafwing-Studios/leafwing-input-manager#247]
## What problem does this solve?

I want to implement keyboard and mouse control for a small game. I would like to give the user the choice of inverting the mouse axes independently from the keyboard input. In ego shooters some people like it to move the mouse forward to look up, others move the mouse backwards to look up.

## What solution would you like?

When setting the `InputMap` it would be nice to be able to set some axes to inverted.

## How could this be implemented?

A boolean `inverted` field in `SingleAxis` might already provide this feature. This can be set to `true` to mark this axis as being inverted.

## What alternatives have you considered?

Currently I implement custom `PitchInverted` action to represent the inverted axis for mouse only. This is a workaround and I would prefer a built-in solution, that is easily switchable by user choice.

## Related work

Using `SingleAxis` to solve this would enable inversion not only for mouse but also for all gamepad axes. Inversion could be useful for them as well.

**Comment by alice-i-cecile** [comment]
I'm on board :) This makes sense to be controlled at the input mapping layer: you don't want to invert mouse motion globally.

**Comment by SignalWalker** [comment]
I have this implemented in a [fork](https://github.com/SignalWalker/leafwing-input-manager), though I'm not sure it's polished enough for a pull request.

**Comment by alice-i-cecile** [comment]
Toss it up in a PR and we can help polish it :)
