### ISSUE TITLE
This crate seems to eat all my buttons click interactions

### ISSUE THREAD

**Issue by maccesch** [Leafwing-Studios/leafwing-input-manager#250]
## Version

0.5.2

## Operating system & version

macOS Monterey 12.6 (M1)

## What you did

Basically tried to use Bevy UI Buttons as show in the example but the `Clicked` interaction never fired (only very randomly and rarely).

## What you expected to happen

I want to be able to receive a `Clicked` interaction from a Bevy UI button.

## What actually happened

Didn't receive the interaction.

**Comment by alice-i-cecile** [comment]
Hmm. Can you make a minimal reproduction? Does this occur with the example given?

**Comment by maccesch** [comment]
Turns out it wasn't the input manager, but the 9-patch lib. Sorry about this!
