### ISSUE TITLE
Chords don't work with `DualAxis`

### ISSUE THREAD

**Issue by djeedai** [Leafwing-Studios/leafwing-input-manager#269]
## Version

0.5.2 and HEAD

## Operating system & version

Win11

## What you did

Change `examples/mouse_motion.rs`:

```diff
- .insert(DualAxis::mouse_motion(), CameraMovement::Pan)
+ .insert_chord(
+     [
+         InputKind::Mouse(MouseButton::Left),
+         InputKind::DualAxis(DualAxis::mouse_motion()),
+     ],
+     CameraMovement::Pan,
+ )
```

and to prevent `unwrap()` from panicking:

```diff
- let camera_pan_vector = action_state.axis_pair(CameraMovement::Pan).unwrap();
-
- // Because we're moving the camera, not the object, we want to pan in the opposite direction
- camera_transform.translation.x -= CAMERA_PAN_RATE * camera_pan_vector.x();
- camera_transform.translation.y -= CAMERA_PAN_RATE * camera_pan_vector.y();
+ if let Some(camera_pan_vector) = action_state.axis_pair(CameraMovement::Pan) {
+     // Because we're moving the camera, not the object, we want to pan in the opposite direction
+     camera_transform.translation.x -= CAMERA_PAN_RATE * camera_pan_vector.x();
+     camera_transform.translation.y -= CAMERA_PAN_RATE * camera_pan_vector.y();
+ }
```

then `cargo run --example mouse_motion`.

## What you expected to happen

Can pan with Left mouse button.

## What actually happened

Nothing.

**Comment by michalmoc** [comment]
I'd like to add that "action_state.pressed(CameraMovement::Pan)" is actually working, returning true when both inputs are triggered.

On the other hand, the axis_pair is not returned despite documentation claiming "Chord inputs will return the DualAxisData of it’s first input." (in my example mouse_motion is the first element of chord).

**Comment by djeedai** [comment]
@alice-i-cecile I just tried again on 0.11.2 the initially posted code, and the dual axis is reported all the time, ignoring the chord. In the original example that means I get some mouse motion without pressing the left mouse button. So I guess this bug needs to be reopened?

**Comment by michalmoc** [comment]
@djeedai I'm not sure I understand, could you perhaps edit test https://github.com/Leafwing-Studios/leafwing-input-manager/blob/7a92892c2a4a091f3273d8a404f37ec8bd5fe113/tests/mouse_motion.rs#L312 to show what is wrong?

**Comment by djeedai** [comment]
Repro with this patch on the `mouse_motion.rs` example (not the test): https://github.com/djeedai/leafwing-input-manager/tree/repro-bug-269

The box moves with mouse cursor moves, ignoring the mouse buttons completely.

**Comment by michalmoc** [comment]
Ok, the problem is with interpretation of return value of `axis_pair`. In the current code, in your example axis_pair() is returning Some, which is not contradictory to the documentation. User is expected to check if the action is `pressed` first, which in the example is not happening. This may be considered error-prone interface, and reported as a separate issue.

**Comment by djeedai** [comment]
Sorry I'm not sure I understand. Are you saying that I need to perform 2 checks (button and axis) to validate if a chord is active? If so, I don't understand what's the point of the chord, since I can achieve the same result without it, by defining two separate actions for the axis and the button? I thought a chord is an abstraction to combine multiple actions into a single virtual one. Can you please show me how the code is supposed to be written for a LMB+drag type of mouse interaction?

Here's my user expectation: If you consider an axis to be active when it's non-zero (outside of dead zone), and a button to be active when it's pressed, then a chord composing of those should be active when both conditions are met, and so should return an axis value only when the button is pressed, no? Or am I misunderstanding what a chord is?

Unity does that with modifiers; the axis is only active when the button is pressed. I think that's a fairly common case to support. Is there any other way to do that which I missed? See https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/ActionBindings.html#one-modifier

**Comment by djeedai** [comment]
Ok I can work around the issue by wrapping the entire check into another check:

```rust
if action_state.pressed(CameraInputAction::Rotate) {
    if let Some(camera_rotate_vector) = action_state.axis_pair(CameraInputAction::Rotate)
    {
        [...]
    }
}
```

But I'd argue that defeats the point of having an abstraction, if the code needs to know that the action has a modifier button. That means also that if the user remaps that action to not having a modifier anymore, then I guess the code breaks?

**Comment by michalmoc** [comment]
My understanding was that `pressed` was a general way to check if an action was triggered. Perhaps you are right and every function of action state must not only return some data but also check if the action is triggered. This is high level design question, we probably should ask original author of action state.
