### ISSUE TITLE
6.0 prints "real clash" to stdout on every clashing input

### ISSUE THREAD

**Issue by Xion** [Leafwing-Studios/leafwing-input-manager#276]
## Version

6.0 from crates.io

## Operating system & version

```
$ uname -a
Linux <redacted> 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## What you did

Upgraded to 6.0

## What you expected to happen

Smooth upgrade, as the changelog didn't seem to indicate any breaking changes

## What actually happened

6.0 prints "real clash" directly to stdout on every clashing input.
It looks like an older debugging code has been accidentally restored in the large 6.0 release commit.

**Comment by alice-i-cecile** [comment]
Ah darn it. I must have messed up the merge conflict. Thanks, I'll fix this up and make a patch release.

**Comment by alice-i-cecile** [comment]
Fixed in https://github.com/Leafwing-Studios/leafwing-input-manager/commit/b564c7e38e4d70ef896380323bd2297aef5d21c8.

New release imminent.
