### ISSUE TITLE
Double-counting of mouse motion and mouse wheel events

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#285]
## Version

#284

## What you did

Run the `mouse_motion` example.

## What actually happened

The console is flooded with messages:

> 2022-11-13T19:35:54.363800Z  WARN bevy_ecs::event: Missed 345 `bevy_input::mouse::MouseMotion` events. Consider reading from the `EventReader` more often (generally the best solution) or calling Events::update() less frequently (normally this is called once per frame). This problem is most likely due to run criteria/fixed timesteps or consuming events conditionally. See the Events documentation for more information.

## Workaround

Silence these notifications by replacing your `DefaultPlugins` with:

```rust
DefaultPlugins.build().set(LogPlugin {
  filter: "wgpu=error,bevy_ecs::event=error".to_string(),
  ..default()
})
```

Huge thanks to Martin for nailing this down: https://discordapp.com/channels/691052431525675048/1034547742262951966/1043564180306919514.

## Additional information

This is due to https://github.com/bevyengine/bevy/pull/5730, as discussed in https://github.com/bevyengine/bevy/issues/6589.

I suspect we're also double-counting events.

**Comment by alice-i-cecile** [comment]
This should only occur with mouse motion and mouse wheels. The other types use `Input`, and so aren't affected.

**Comment by alice-i-cecile** [comment]
Spam is gone with Bevy 0.9.1, but the underlying double counting is still there.

**Comment by Inspirateur** [comment]
The issue seems to have gotten worse with bevy 0.12.1 !
I'm quoting Ira (`devil_ira`) on discord here
> Turns out leafwing input manager isn't using eventreaders internally as it should. So it was double counting events before, but with some changes 0.12.1 it could be re-reading the same events tens of times

I'm using it for camera panning (exactly as the leafwing example does it) and after updating to bevy 0.12.1 i'm getting crazy values in the thousands from DualAxis::mouse_motion() even when my mouse is not moving at all :(
