### ISSUE TITLE
Deadzone drift/weirdness

### ISSUE THREAD

**Issue by ndarilek** [Leafwing-Studios/leafwing-input-manager#336]
## Version

https://github.com/ndarilek/leafwing-input-manager/tree/deadzones

## Operating system & version

Windows 11

## What you did

I added movement controls to the left stick with a deadzone and noticed the following behaviors:
* With a deadzone if 0.5, moving my stick up and ever so slightly to the right/left but below the deadzone threshold generates an input representing both the up motion and the right/left motion.
* Releasing the stick seems to still generate inputs in spite of the deadzone, and the values I get are below the threshold. The action also doesn't register as released.

## What you expected to happen

* If my axis values are something like (1, 0.05) with a deadzone of 0.1, then the final values should be (1, 0) not (1, 0.05).
* A dual-axis value should register as released when the deadzone for both values drops below the deadzone threshold. It should also return a value of (0, 0).

## What actually happened

My movement systems apply a penalty for any left/right strafing motion. If I set a deadzone to 0.1, moving the stick directly up but even slightly to the left/right triggers strafe detection since the value is something like 0.03. But this value is beneath the deadzone threshold, so I think this behavior is incorrect.

Additionally, once I use a stick at all, my character seems to drift around once the stick is released. I'm seeing axis values below the deadzone thresholds and the action isn't released. I don't think this is controller drift since it only happens after I use the stick once, and doesn't ever stop regardless of how high I set the deadzone.

## Additional information

It's possible that I'm misunderstanding something. https://github.com/ndarilek/leafwing-input-manager/tree/deadzones has 2 failing tests that illustrate the issue. The first sends an input value to the app below the deadzone threshold, but the action doesn't register as released. The second sends an axis value where one is above the threshold and the other is below. In this instance I'd expect the action to show as pressed, but the value below threshold to be 0.0 rather than the set value of 0.05.

Thanks.

**Comment by ndarilek** [comment]
I'd like to take a crack at a fix since this is blocking a release for me, but I'm not clear what the right approach is. In particular, #316 seems relevant here.

I looked around the code a bit and can't seem to find where axis values might be translated into pressed/release state. If anyone can point me to where that happens, or where it should happen if it doesn't, I'd appreciate it.

Thanks.

**Comment by ndarilek** [comment]
Sorry for all the noise, just trying to keep this issue updated with my investigations:

I'm looking at `InputStreams` as it definitely seems to have code that would fail this test (I.e. only checks for `len() != 0.` to determine if something is pressed.)

But it doesn't appear to get called from the test case. So either it isn't included at this low level and maybe deadzone checks shouldn't happen here, or I'm on the wrong path entirely.

**Comment by alice-i-cecile** [comment]
Thanks for taking a look! I'd be happy to see this fixed, but don't immediately know where to look.

If you can get a failing test case that would be exceptionally helpful.

**Comment by ndarilek** [comment]
The linked branch has two that I just added. Or did you mean something else?

**Comment by ndarilek** [comment]
This should be fixed now, so closing.
