### ISSUE TITLE
Axis values support for network diffs

### ISSUE THREAD

**Issue by paul-hansen** [Leafwing-Studios/leafwing-input-manager#342]
We used the network diffing functionality of this library for our game jam game: https://prawl.itch.io/stellar-squeezebox which overall turned out great and it was really helpful for getting something off the ground quick!

Unfortunately, gamepad support was really lacking when diffing actions with a couple major issues:

A. There is no support for axis data for ActionDiff
B. ~~If you use an axis as a button (e.g. turn left) you can't set a deadzone or it stops being recognized on the server. Example:
  `SingleAxis::negative_only(GamepadAxisType::LeftStickX, 0.1).with_deadzone(deadzone)`~~ Was user error. See [comment](https://github.com/Leafwing-Studios/leafwing-input-manager/issues/342#issuecomment-1510452715)
  
I'd like to contribute towards this, so if you have any thoughts about how you want this to work let me know. (I'll probably taking a few days to relax now that the jam is over, so might be a bit)

**Comment by paul-hansen** [comment]
Looks like that's a bit of an undertaking but I would be totally down with helping out with it.

**Comment by paul-hansen** [comment]
Discovered that problem B was mostly user error. `.with_deadzone()` shouldn't  be used with `SingleAxis::negative_only` instead I should have been adjusting the threshold value passed to `SingleAxis::negative_only` which needed to be negative. I think this would have caused issues under non-networked use too. I should have made a minimal repo to test and would have caught this, was just lazy after cramming for the jam. 
Gamepads are working for our game now! Just have to treat everything as a button since there isn't axis data in actiondiffs.

**Comment by TimJentzsch** [comment]
> Discovered that problem B was mostly user error. `.with_deadzone()` shouldn't be used with `SingleAxis::negative_only` instead I should have been adjusting the threshold value passed to `SingleAxis::negative_only` which needed to be negative. I think this would have caused issues under non-networked use too. I should have made a minimal repo to test and would have caught this, was just lazy after cramming for the jam. Gamepads are working for our game now! Just have to treat everything as a button since there isn't axis data in actiondiffs.

Is this behavior documented properly?
Might be worth it to open up a doc issue for this in case that others might run into the same problem :)

**Comment by paul-hansen** [comment]
It kind of is, but you have to think about what it's saying and already understand what the values on SingleAxis mean.


> Creates a [SingleAxis](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/axislike/struct.SingleAxis.html) with the axis_type and negative_low set to threshold.
>
> Positive values will not trigger the input.

[Source](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/axislike/struct.SingleAxis.html#method.negative_only)

Could probably be improved to help avoid it being a footgun.
