### ISSUE TITLE
Inaccurate rotation

### ISSUE THREAD

**Issue by 0HyperCube** [Leafwing-Studios/leafwing-input-manager#353]
## Version
Latest main 283030391d49c97c54d714d299f62f97f037c26f

## What you did

Rotation with middle mouse button in Emergence with a high frame rate is not reliable.

## Additional information

This is because the `Rotation` is truncated to one tenth of a degree, which is not enough precision. This could either be raised to a hundredth of a degree (keeping with u16) or a millionth of a degree (with u32).

**Comment by alice-i-cecile** [comment]
Let's go with a u32: I don't think the cost is significant in these applications.
