### ISSUE TITLE
mouse_position example system runs in Startup instead of Update

### ISSUE THREAD

**Issue by sapir** [Leafwing-Studios/leafwing-input-manager#367]
## What problem did the developer encounter?

I tried using code from the mouse_position example but the update system wasn't running.

## What was the fix?

Modify the stage at https://github.com/Leafwing-Studios/leafwing-input-manager/blob/8904e1ea54809aa61c0150345fcf16032b59609b/examples/mouse_position.rs#L12 from Startup to Update.

(edit: or should it be PreUpdate?)

**Comment by alice-i-cecile** [comment]
Yep, update is fine. I'd be happy to accept a PR!
