### ISSUE TITLE
Bevy versioning/compatability table in README

### ISSUE THREAD

**Issue by BenedictWilkins** [Leafwing-Studios/leafwing-input-manager#402]
Many other bevy plugin repositories have a versioning table (e.g. https://github.com/StarArawn/bevy_ecs_tilemap), its really helpful to know which releases correspond to which bevy version. I couldn't see this documented anywhere, in the README.txt would be a good place. 

I see that the versions of the plugin look suspiciously like bevy version numbers, is this made explicit anywhere? (I cant see a release for 0.11, which I why I am opening the issue).

**Comment by alice-i-cecile** [comment]
> I see that the versions of the plugin look suspiciously like bevy version numbers

This is just an unfortunate coincidence: 0.10 of leafwing-input-manager corresponds to Bevy 0.11.

**Comment by mgi388** [comment]
@alice-i-cecile this was done in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/465 and can be closed I think.
