### ISSUE TITLE
Disabling InputMaps for inactive states

### ISSUE THREAD

**Issue by huhlig** [Leafwing-Studios/leafwing-input-manager#41]
## What problem did the developer encounter?

Looking for how to disable handling inputs for states/entities not currently active without removing components. 

## What was the fix?

Unknown

## How could this be better documented?

Currently Undocumented.

**Comment by alice-i-cecile** [comment]
This is mostly blocked by https://github.com/bevyengine/bevy/issues/2160. Ideally we'd be able to just configure all of the input map plugin systems to run in the given state. https://github.com/bevyengine/rfcs/pull/45 will largely resolve this.

**Comment by alice-i-cecile** [comment]
Workaround created!

Use `InputManagerPlugin::run_iff_state` when adding your plugin.
