### ISSUE TITLE
ToggleActions is a resource, even with InputMap as component

### ISSUE THREAD

**Issue by NiseVoid** [Leafwing-Studios/leafwing-input-manager#416]
## Which feature is frustrating to use or confusing?

Using ToggleActions feels unnatural to use, and could lead to problems in some couch co-op scenarios, with component-based input maps, because they are all resources that apply globally.

## Expectation

ToggleActions as components, or maybe a way to toggle the input maps directly?

**Comment by Veritius** [comment]
I think that `ToggleActions<T>` should be both a resource *and* a component. This lets you implement a 'paused' state by adding the resource, affecting all entities, but also letting you enable/disable it per-entity.

**Comment by alice-i-cecile** [comment]
Totally agree.

**Comment by benfrankel** [comment]
It seems like this would be fixed by https://github.com/Leafwing-Studios/leafwing-input-manager/pull/456.
