### ISSUE TITLE
Unable to use InputMap as an asset

### ISSUE THREAD

**Issue by barsoosayque** [Leafwing-Studios/leafwing-input-manager#423]
## Version

[0.11.2](https://github.com/Leafwing-Studios/leafwing-input-manager/commit/1617f40782323838e7e951a5e2234e6285ed8132)

## Operating system & version

NixOS (master)

## What you did

Updating to bevy 0.12 / leafwing-input-manager 0.11.2

## What you expected to happen

`Handle<InputMap<A>>` generates no errors, as it was valid before to use `InputMap` as an asset.

## What actually happened

My code that used `InputMap<A>` as an asset (e.g. `Handle<InputMap<A>>`) is not working anymore.

## Additional information

Apparently assets now should derive `Asset` instead of `TypeUuid`, and although it is a simple change, it unravels an issue I tried to fix in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/386, because `Asset` requires `TypePath`, which can be provided by `Reflect`. And even though version 0.11 mentions that `InputMap` should be `Reflect` now, as far as I can tell it's not ?

**Comment by alice-i-cecile** [comment]
Thanks for the report! And yeah, the latest 0.11 version is a bit screwed up. I'll take a look!

**Comment by barsoosayque** [comment]
What would be the best course of action here ? I might reopen and port to multimap #386, if that is a good solution ? I would be glad to work on this and resolve it asap but I'm not sure what to actually do

**Comment by alice-i-cecile** [comment]
Yep, redoing the change in #386 on the latest main is correct.
