### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by djeedai** [Leafwing-Studios/leafwing-input-manager#429]
Here's a list of feedbacks around the documentation of input actions and chords, and other related concepts, gathered while investigating #269.

# [`UserInput`](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/user_input/enum.UserInput.html#)

Both `Single` and `Chord` are documented in terms of the concept of "button", but accept the more generic concept of `InputKind` as associated data instead. In particular `Chord` states:

```txt
A combination of buttons, pressed simultaneously
```

This concept of "pressed" doesn't map to several input kinds like `SingleAxis`, `DualAxis`, or `MouseWheelDirection`.

# [`DeadZoneShape`](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/axislike/enum.DeadZoneShape.html)

There's no explanation of what the dead zone does to the mapping. This is especially problematic for the `Cross` variant, as I don't understand how that can map a 2D vector continuously from a non-continuous shape.

A classic dead zone circle remaps the distance to the axes center. So for a radius `r=0.5`, we get a mapping `0..0.5 -> 0.` inside the deadzone, and `0.5..=1` -> `0..=1` outside it. That is, the boundary of the deadzone maps to `0` and the max range maps to `1.`.

For a `Rect`, I can imagine how the concept extends by treating each axis separately. This is equivalent to using a different distance metric (Manhattan L1 distance, instead of Euclidian L2 distance).

For a `Cross`, I have no idea. It sounds like the mapping would be discontinuous.

# Chord and [`ActionState`](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/action_state/struct.ActionState.html)

As mentioned in #269 the concept of chord seems to be loosely defined. It looks like it groups only buttons, or only axes, but not heterogeneous inputs?

- The `Chord` docs mention combining multiple buttons. It doesn't talk about non-button inputs.
- `ActionState::axis_pair()` docs says that the first `DualAxis` input will be returned, which sounds like it doesn't combine anything.
- But then the next sentence says that values for multiple axes will be added together. Which is further reinforced via the `clamped_axis_pair()` API.
- There's no explanation about what happens when the chord contains heterogeneous inputs like a button and an axis. As seen in #269, apparently there's no grouping at all, and the user has to manually check both, which means the abstraction breaks and the code is now linked with the action configuration, and cannot be remapped.

# [`InputKind`](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/user_input/enum.InputKind.html)

All input kinds should probably document precisely the range of values they return and how this relates to the underlying physical device (like, what's the "discretized mouse movement", is it a physical pixel or logical one?), the type of input (since it seems axes and buttons are treated differently; see above), and any extra specific details (dead zone, _etc._). This enum is one of the central pieces for the crate user to understand. There are vague references to things like "continuous motion" which are also not explained (what are the implications of being "continuous"?). I'm assuming the opposite is the "buttonlike-input" mentioned in [`MouseMotionDirection`](https://docs.rs/leafwing-input-manager/latest/leafwing_input_manager/buttonlike/enum.MouseMotionDirection.html)?

**Comment by alice-i-cecile** [comment]
Super helpful. This ties back into some of my existing ideas about how we should be restructuring things somewhat to split apart continuous and button-like inputs.

**Comment by crvarner** [comment]
Has there been any further discussion on the behavior of `DualAxis` within chords? I agree with @djeedai that the current behavior breaks the abstraction, as code cannot be written for continuous inputs without knowledge of whether a modifier is required.

My expectation was that in the case of a chord that was not fully triggered, `axis_pair` would return `None`.
```
        if let Some(axis) = action_state.axis_pair(&Action::RotateCamera) {
            // my chord is active and axis contains the DualAxis data
        } else {
          // either my DualAxis is in the dead zone OR my modifier is not pressed
        }
```
