### ISSUE TITLE
Two inputs (WASD, Mouse button + Mouse Movement) that trigger an action, mouse movement will ignore the chord

### ISSUE THREAD

**Issue by gak** [Leafwing-Studios/leafwing-input-manager#430]
## Version

0.11.2

## Operating system & version

macOS 14.1.2

## What you did

I have an InputMap that goes into a resource:

```rust
 InputMap::new([
            (UserInput::VirtualDPad(VirtualDPad::wasd()), Self::Move),
            (
                UserInput::Chord(vec![
                    InputKind::Mouse(MouseButton::Middle),
                    InputKind::DualAxis(mouse_motion()),
                ]),
                Self::Move,
            ),
            // other inputs...
        ])
```

Usage in the system:

```rust
fn camera_movement(
    time: Res<Time<Real>>,
    mut action_state: ResMut<ActionState<PlayerAction>>,
    mut camera: Query<(&mut Transform, &OrthographicProjection), With<Camera>>,
) {
    if !action_state.pressed(PlayerAction::Move) {
        return;
    }

    let Some(axis) = action_state.axis_pair(PlayerAction::Move) else {
        return;
    };

    let (mut camera_transform, projection) = camera.single_mut();

    let velocity = axis.xy() * projection.scale;
    camera_transform.translation += velocity.extend(0.);
}

```

These two work as expected separately:
1) WASD will move the camera.
2) Holding down middle mouse button while moving the mouse will move the camera.

But when I hold down one of the WASD keys and move the mouse...

## What you expected to happen

Moving the mouse while pressing any WASD keys should ignore the mouse.

## What actually happened

When I:
1) Hold down one of the WASD keys and
2) Move the mouse and
3) Don't hold down the middle mouse button

... it activates the mouse movement.

**Comment by gak** [comment]
Another situation which I was going to report as a separate bug, but realised it's probably the same bug:

```
            (
                UserInput::Chord(vec![
                    InputKind::Mouse(MouseButton::Middle),
                    InputKind::DualAxis(mouse_motion()),
                ]),
                Self::Move,
            ),
            (
                UserInput::Chord(vec![
                    InputKind::Keyboard(Space),
                    InputKind::DualAxis(mouse_motion()),
                ]),
                Self::Move,
            ),
```

Having these two will make the axis_pair value go twice as fast, as if the other chord modifier was ignored. So both mouse_motion()'s "activate" even though I might only be holding down space and not middle mouse.

**Comment by Dzjudieng** [comment]
I'm having the same problem but it seems to be easy to fix?

**Comment by alice-i-cecile** [comment]
I'd be happy to see a PR for this.
