### ISSUE TITLE
Remove strum dependency

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#44]
This will require us to:

1. Removing the `IntoEnumIterator` trait, rolling the `iter` method into `Actionlike`
2. Add the `EnumIter` macro to the `Actionlike` enum.

In exchange, users will be able to remove the `strum` dependency, and reduce their derive spam by one trait.

While we're at it, we should add a `upper_bound() -> u32` trait, unblocking #39. 

Incidentally, this strategy will enable users to manually implement the trait for non-enum action types, which can be very useful for open-ended sets of inputs.

**Comment by Shatur** [comment]
But if I already use strum in my project, I will have duplicated functionality provided by `Actionlike` :(

**Comment by alice-i-cecile** [comment]
Yes, but that's by far the lesser of evils here IMO.
