### ISSUE TITLE
ActionDiffs are not being networking correctly when an action is consumed

### ISSUE THREAD

**Issue by cBournhonesque** [Leafwing-Studios/leafwing-input-manager#443]
## Version

[The release number or commit hash of the version you're using.](https://github.com/Leafwing-Studios/leafwing-input-manager/commit/cda8d12b2c25ec39b3fb57911d5b9591eadb9224)

## What you did

In my `Update` schedule, I have something like:
```
if action.pressed(PlayerActions::Shoot) {
   action.consume();
}
```
and in `PreUpdate`, I generate `ActionDiffs` using the diff-generation system after `InputSystemSet::Update`.

However I don't get any diffs for the action that was consumed.

My understanding is that the flow is this:
- Frame 1: user presses button
  - PreUpdate: PressButton, Shoot is `pressed`
  - Update: Shoot is `consumed` (`consumed=true` and `state=JustReleased`)
- Frame 2
  - PreUpdate: Tick, so we go from `JustReleased` to `Released`
  - PreUpdate: in generate-diffs, we only network JustReleases, so this is not networked
...
- Frame X: user releases button
  - PreUpdate: `consumed=false`. `state=Released` and not `JustReleased` because the button was already marked as `Released`. The diff-generation system only networks `JustReleased` events, so I never get the information that the key was released.

## What you expected to happen

The release of the button is networked, either when the button is consumed, or when I actually released the key.

## What actually happened

Nothing is networked.

## Potential solutions:

- I could try to be more clever in where I use the diff-generation system (maybe run it once before `InputSystem::Tick` as well so that the consumed action is still JustReleased

- Maybe when a key was consumed, we still trigger a `JustReleased` when the actual key is `Released`.
(so `release()` would be something like:
```
if *self != ButtonState::Released || self.consumed {
            *self = ButtonState::JustReleased;
}
```

- maybe in the diff generation system, we send a `release` diff for every action that is consumed, even if it's not a `JustRelease`. We could get potentially a lot of duplicate `Release` `ActionDiffs`, but it's a good short-term solution

**Comment by Shute052** [comment]
isn't this fixed by #480?

**Comment by cBournhonesque** [comment]
Nope; the problem is not with the `consume` function, it's more about how ActionDiffs are generated.

the problem is that consumed actions are immediately marked as JustReleased, and then become `Released` in the next frame (because we tick them once).
The generate_action_diffs runs after that and doesn't generate diff for them, since it only generates diffs for `JustReleased` and `JustPressed` actions.

Personally I have a solution that creates action diffs for `JustRelease OR (Released && Consumed)` actions, but I don't like it that much because it generates an `Released` `ActionDiff` every frame until the key is actually released.

Maybe another solution would be to have a `generate_action_diff_for_consumed` system that runs before `InputManagerSystem::Tick` and a `generate_action_diff` system that runs after `InputManagerSystem::Tick`

**Comment by cBournhonesque** [comment]
Yes I don't think it's a priority, especially because the system is not added in the plugin itself so users can just use it for reference but roll out their own implementation
