### ISSUE TITLE
Held inputs become `JustPressed` when `ToggleActions` is enabled

### ISSUE THREAD

**Issue by benfrankel** [Leafwing-Studios/leafwing-input-manager#446]
## Version

`leafwing-input-manager` 0.11, bevy `0.12`.

## Operating system & version

Arch Linux

## What you did

Setup: `KeyCode::R` is mapped to `GameAction::Restart`, with a system that restarts the game on `action_just_pressed(GameAction::Restart)`. Additionally, there is a system that disables `GameAction` on `KeyCode::Slash` and re-enables it on `KeyCode::Return`.

I press `/` to disable `GameAction`, then press and hold `R`, then press `Return` while `R` is still held.

## What you expected to happen

When `GameAction` is re-enabled, the action state for `GameAction::Restart` should go from `Released` to `Pressed` -- because `R` is still being held from an earlier press -- thus not triggering a game restart.

## What actually happened

The game action went to `JustPressed`, triggering a game restart.

**Comment by benfrankel** [comment]
Another example that doesn't demonstrate the cause as cleanly, but was the original issue I ran into:

I can also press `KeyCode::Escape` to re-enable `GameAction`. But I also have `KeyCode::Escape` mapped to `GameAction::Pause`, with a system that pauses the game on `action_just_pressed(GameAction::Pause)`. As a result, whenever I use `KeyCode::Escape` for this it instantly (next frame) pauses the game as well.

**Comment by alice-i-cecile** [comment]
Great explanation and reproduction, thank you!

**Comment by Shute052** [comment]
The main problem likely originates from `systems::release_on_disable()`, which releases all buttonlike without storing their current `Pressed` states for restoration on re-enabling. A straightforward fix might be possible?

**Comment by benfrankel** [comment]
One possible solution is adding `ActionState::disabled: bool`, and continuing to update action states even while they're disabled. Then functions like `ActionState::just_pressed` can take `disabled` into account.

**Comment by alice-i-cecile** [comment]
> EDIT: Actually, if this approach is taken, it could probably just replace the ToggleActions resource entirely.

This is appealing to me.

**Comment by benfrankel** [comment]
Made a PR for the other approach. I haven't tested it yet, though.
