### ISSUE TITLE
Function run_in state causes crash

### ISSUE THREAD

**Issue by Shatur** [Leafwing-Studios/leafwing-input-manager#46]
## Version

0.1.2

## Operating system & version

ArchLinux

## What you did

I tried the following example from docs:

https://github.com/Leafwing-Studios/leafwing-input-manager/blob/c5e59de1d73aa12cb90165fcd954f62f04dc4ca9/src/lib.rs#L116-L141

But it crashes if I add a state and call a single update. So the documentation test is valid only because `update()` is not called.

## What you expected to happen

Plugin runs only in specified state

## What actually happened

```
thread 'main' panicked at 'Resource requested by <leafwing_input_manager::InputManagerPlugin<input_test::PlayerAction, input_test::GameState> as bevy_app::plugin::Plugin>::build::{{closure}} does not exist: input_test::GameState', /home/gena/.cargo/
registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.6.0/src/system/system_param.rs:326:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information

Minimal example that should work, but crashes:
[main.rs](https://github.com/Leafwing-Studios/leafwing-input-manager/files/7945836/main.txt)

**Comment by alice-i-cecile** [comment]
Ah, I forgot to actually add the state in the doc test. Oops!

**Comment by Shatur** [comment]
> I forgot to actually add the state in the doc test.

It's not the only issue. In the `main.rs` attached above, I added the state, but the same crash still happens. I think this is because state is not a resource. I think we need to use `State<T>`.

**Comment by alice-i-cecile** [comment]
Right. Unfortunately, `State` is not object-safe, so I'm not immediately sure we can do that. I'll take a look.
