### ISSUE TITLE
Document feature flags

### ISSUE THREAD

**Issue by johanhelsing** [Leafwing-Studios/leafwing-input-manager#461]
## What problem did the developer encounter?

I ran into #421, and it seems I can work around it by enabling the `ui` and `block_ui_interactions` cargo features, however without reading the source code, it's unclear to me what these flags do and if they affect my app in an undesired way (apart from adding a bevy_ui dep)

## How could this be better documented?

Maybe it would be possible to explain it here?

https://docs.rs/crate/leafwing-input-manager/0.11.2/features

**Comment by alice-i-cecile** [comment]
Oh super interesting. I don't know if / how we can generate docs that will show up there.

That said, we should definitely document these. Unless there's an answer to the above question, that belongs in the `Cargo.toml` where the flags are defined.

**Comment by Shute052** [comment]
Unfortunately, writing documentation on the features page of the docs.rs is unfeasible. This limitation stems from the Rust official docs.rs generator, which exclusively compiles feature flags alongside their respective sub-features. Please refer to its [template](https://github.com/rust-lang/docs.rs/blob/master/templates/crate/features.html) for more details.

**Comment by alice-i-cecile** [comment]
https://github.com/rust-lang/rust/issues/96318 seems to be the upstream issue to follow.
