### ISSUE TITLE
Broken link to examples

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#482]
This link https://docs.rs/leafwing-input-manager/0.13.1/leafwing_input_manager/examples is broken.

We need to swap to an absolute path.

**Comment by Shute052** [comment]
Replace it with https://github.com/Leafwing-Studios/leafwing-input-manager/tree/latest/examples? And I think it's better to update the feature flags in the `Cargo.toml` file accordingly.

**Comment by alice-i-cecile** [comment]
Agreed on both.
