### ISSUE TITLE
Add arpeggios

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#49]
Needs:
- internal state on InputMap (related to #48)
- timeout detection

**Comment by johanhelsing** [comment]
How will arpeggios work? will it be able to say that
- ctrl down, alt down, p down should trigger the action
- alt down, ctrl down, p down should trigger the action
- p down, ctrl down, alt down should not trigger the action

Or maybe I'd need to add two arpeggios? one for alt+ctrl and one for ctrl+alt?

**Comment by alice-i-cecile** [comment]
> Or maybe I'd need to add two arpeggios? one for alt+ctrl and one for ctrl+alt?

This is the idea. I intend to add builder methods to make that easy, along with a reasonable "modifier key" setup which does this automatically.

If there were likely to be arpeggios of more than three inputs, with this sort of branching logic, I'd add a graph-builder API, but I think that's dramatically over-engineering here 😄

**Comment by alice-i-cecile** [comment]
Arpeggios should chain as long as there no gap between adjacent inputs.

**Comment by alice-i-cecile** [comment]
Closing in favor of #485.
