### ISSUE TITLE
Handle 2-dimensional analogue input

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#50]
There are three main use patterns for this:

1. Partition the analog space into digital buttons
   - Handle with a mapping API that sets thresholds/boundaries for the values
2. Map analog values into actions, but still use the raw analog value for something (like smoothly changing walk/run on an analog stick)
   - Actually a special case of 1: You map onto an action, but then get back the analog value that generated that action
      - This can be done with reverse mapping, or with forward propagation
   - Destructuring this value ain't gonna happen
   - But we can return out the values from the virtual button if we store it
   - We actually don't need to return the value itself, just the user input that triggered it (since then the caller can look up the correct value themselves)
   - Requires #76
3. Mapping analog values to an action simply does not make sense (flight stick tilt)
   - Not our problem- can add helper features to `bevy_input` if necessary
      - In particular, "get a Vec2 from a particular axis" is an extremely common operation that is unnecessarily painful 

Eventually this should support:
- all gamepad axes
- touch emulated joysticks
- mouse emulated joysticks

**Comment by Shatur** [comment]
Looking forward to it. Are you planning it for 0.2?

**Comment by alice-i-cecile** [comment]
Probably not; it's a bit complex and I'd rather not block other important features and releases. We'll see though!

**Comment by shanesveller** [comment]
Do you also consider `MouseWheel` events in scope here?

**Comment by alice-i-cecile** [comment]
Hmm. That's a good question. Maybe? I suppose they could be used in similar ways.

Mostly though I think mouse wheel events act like a virtual button that can be held down instead though.

**Comment by alice-i-cecile** [comment]
Completed.
