### ISSUE TITLE
Being able to add `InputManagerPlugin` for both client and server in the same app

### ISSUE THREAD

**Issue by cBournhonesque** [Leafwing-Studios/leafwing-input-manager#503]
## What problem does this solve?

I'm working on a networking library: https://github.com/cBournhonesque/lightyear
and I use leafwing-input-manager to network inputs.

I'm working on a feature where the app can run in a `unified` mode: both the client and the server are running in the same app.
This can be useful to have one player act as a host/server.
It can also be useful to develop a game where the singleplayer mode uses the same code organization as multiplayer (a local client which talks to a local server in the same app).

One issue I'm having is that I cannot add the same plugin `InputManager<A>` twice  (once as client and once as server).
I wonder if it could be changed to allow multiple registrations:
- one option could be to accept a marker component `InputManager<A, Mode>` where `Mode=Server` or `Mode=Resource`
- another option could be to simply override the `Plugin::is_unique` to be `false`
- another option could be to provide a `ClientInputManager` and `ServerInputManager` plugins

**Comment by alice-i-cecile** [comment]
> > another option could be to simply override the Plugin::is_unique to be false

I would prefer this as a minimally invasive solution. Feel free to submit a PR: just add a doc comment explaining why this value is overridden.

Would this actually solve your problem though? Don't you need to be able to insert the systems into two different schedules, one for the server and another for the client? Without a way to configure which schedules the systems are added to, it seems difficult to actually make use of two copies of the plugin.

**Comment by cBournhonesque** [comment]
Thanks for your response;
I will think about it more.
The server plugin seems to just tick the states (which is already done at the start of the client plugin), so it sounds like I can get away with just registering the client plugin!

**Comment by alice-i-cecile** [comment]
Closing as not-planned for now: please feel free to reopen if you need it.
