### ISSUE TITLE
Compilation in headless mode

### ISSUE THREAD

**Issue by sapir** [Leafwing-Studios/leafwing-input-manager#508]
## What problem does this solve?

Use types from `leafwing-input-manager` in a headless server that shares code with a graphical client.

## What solution would you like?

Could the `bevy/bevy_gilrs` feature be made optional? `leafwing-input-manager` seems to compile fine without it.

**Comment by alice-i-cecile** [comment]
Yep, I'd be happy with a PR to do this.
