### ISSUE TITLE
Put the 'Timing' field of 'ActionState' behind a feature

### ISSUE THREAD

**Issue by cBournhonesque** [Leafwing-Studios/leafwing-input-manager#525]
## What problem does this solve?

There are a lot of games that don't need information about timings, but simply about button presses.
It would improve performance + bandwidth (for networking) if the timing fields were put behind a feature.

If the feature is off, the field wouldn't get any timing information, and it would not get updated at all.

**Comment by alice-i-cecile** [comment]
Agreed! I would happily merge a PR for this.
