### ISSUE TITLE
Split UserInput into multiple traits

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#535]
I had previously considered splitting it into different input kinds: Button, Axis, DualAxis, etc.; and there are corresponding data types for each. Then, modify the ActionState API, something like this:
```
if let ButtonState(state) = action_state.get(ButtonAction) {
   let pressed = state.pressed;
   let pressure = state.pressure; // Gamepad buttons are ranging from 0 to 1, and others are 0 or 1
}
if let AxisValue(value: f32) = action_state.get(AxisAction) {
}
```

_Originally posted by @Shute052 in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/490#discussion_r1632406354_

**Comment by alice-i-cecile** [comment]
The basic design I'm going to go with is a core `UserInput` trait with the bare minimum of functionality.

Then, three other traits that imply `UserInput`: `ButtonlikeInput`, `SingleAxisInput`, `DualAxisInput`.

**Comment by Shute052** [comment]
I was thinking of having an `InputData` enum for buttons, single-axis inputs, and dual-axis ones.
However, there's an issue with Chord in that context. It can consist of multiple single-axis inputs and multiple dual-axis inputs (but only considers the first dual-axis data).

**Comment by alice-i-cecile** [comment]
Yeah, I think that we need to restrict chords to only contain buttonlike inputs, and then make sure there's general-purpose ways to turn axislikes into buttonlikes.

I'll tackle this and ping you for review :)

**Comment by Shute052** [comment]
> I think that we need to restrict chords to only contain buttonlike inputs

But in some cases, Chord with single/dual-axis inputs can be really useful. For instance, in my project, I've implemented mouse drag using a Chord.

Perhaps we could consider making a Chord consist of either only buttons, only buttons with single-axis inputs, or only buttons with dual-axis inputs?

**Comment by alice-i-cecile** [comment]
Hmm 🤔 Okay, I'll leave it for now and chew on it.
