### ISSUE TITLE
Make `Trigger::entity()` panic on `Entity::PLACEHOLDER` and add `Trigger::get_entity()`

### ISSUE THREAD

**Issue by MiniaczQ** [Leafwing-Studios/leafwing-input-manager#558]
## What problem does this solve?

Trying to perform commands on trigger entity can lead to errors later than expected (command execution instead of call site).

## What solution would you like?

While `Entity::PLACEHOLDER` works great for the internals, the users should be presented with the standard two methods:
- `entity()` - get a valid entity or panic
- `get_entity()` - get a valid entity or none

This requires a breaking change on `entity()` which currently never panics, but can return `Entity::PLACEHOLDER`.

## What alternatives have you considered?

Check for placeholder by oneself.

**Comment by alice-i-cecile** [comment]
Is this the right repo for this? This seems like a Bevy bug for observers.

**Comment by MiniaczQ** [comment]
You're right, I opened the wrong tab
Well, this explains the different issue template i guess
