### ISSUE TITLE
Have an easy way to see if an entire ActionLike is disabled

### ISSUE THREAD

**Issue by cBournhonesque** [Leafwing-Studios/leafwing-input-manager#563]
## What problem does this solve?

https://github.com/Leafwing-Studios/leafwing-input-manager/pull/456 changed the way that disabling actions was handled, from using a `ToggleActions<A>` resource to adding a `disabled` flag **per Action** (not ActionState)
I think there still should be a way to disable an entire `ActionLike`.

Currently we only have the method `disabled(a: &Action)` to check if a given Action is disabled, but very often we would want to check quickly if the entire set of Actions is disabled for a given entity.

One use-case: in networking, if the entire set of actions is disabled, I would like to stop sending network packets for a given entity.
I guess currently I could iterate through all Actions and check if all of them are disabled, but that doesn't seem elegant.

## What solution would you like?

Maybe the `ActionState` should contain additional data that is shared between all Actions, on top of the existing HashMap
```
pub struct ActionState<A: Actionlike> {
    /// The [`ActionData`] of each action
    action_data: HashMap<A, ActionData>,
}
```

Something like
```
pub struct ActionState<A: Actionlike> {
    /// The [`ActionData`] of each action
    action_data: HashMap<A, ActionData>,
    disabled: bool,
}
```
(disabled could be a nested Metadata field)

Then I could easily disable the entire ActionState, instead of disabling each Action individually.

## Related work

Related to https://github.com/Leafwing-Studios/leafwing-input-manager/issues/553

**Comment by benfrankel** [comment]
There are 3 levels: `Actionlike`, `ActionState`, and `Action`. Disabling is currently at the `Action` level, and was previously at the `Actionlike` level. Maybe there's value in having all three, or maybe it's not worth the complexity, IDK.

**Comment by cBournhonesque** [comment]
There's a lot of cases where we'd like the entire `ActionState` or `Actionlike` to be disabled: when the user is in a cutscene, etc.
I think it would be worthwhile to add
