### ISSUE TITLE
ActionState<A>::value can no longer, since version 0.15.0, be used to query for value of triggers.

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [Leafwing-Studios/leafwing-input-manager#585]
## Version

0.15.0

## Operating system & version

Fedora 40 Workstation

## What you did

Defining an action `Action::A` to be an `InputControlKind::Button`, I tried to query its value using `action_state.value(&Action::A)`.

## What you expected to happen

The program reads the trigger value, as is supposed to be shown in the example [`axis_inputs`](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/examples/axis_inputs.rs).

## What actually happened

The program crashes with an assertion error, as  `Action::input_control_kind(&Action::A) != InputControlKind::Axis`.

## Additional information

Note that `ActionState::value` has the assertion that `Action::input_control_kind(&Action::A) == InputControlKind::Axis` (see [this line](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/a97e2cb73036e22ca64f915516fe8d543526ab92/src/action_state/mod.rs#L477)), which is clearly false for the defined action. Note that the example [`axis_inputs`](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/examples/axis_inputs.rs) also crashes on the main branch (as of Thursday, 8th of August 2024) for the exact same reason, and thus should work as a reproducible example.

**Comment by alice-i-cecile** [comment]
IMO the fix here is #551 :)

**Comment by Invisible-Rabbit-Hunter** [comment]
I actually just noticed that the `axis_inputs` example fails even earlier, due to a similar issue, where `ActionState::pressed` is used for both `InputControlKind::DualAxis` and `InputControlKind::Axis`, which causes an assertion to fail.
