### ISSUE TITLE
Crash on several examples

### ISSUE THREAD

**Issue by giusdp** [Leafwing-Studios/leafwing-input-manager#591]
## Version

v0.15

## Operating system & version

MacOS 14.5

## What you did

Cloned the repo, checked out to tag v0.15 and ran the examples one at a time.

## What you expected to happen

The examples working.

## What actually happened

The examples crashed.

## Additional information

I'll list the examples that crashed with the relative errors:

- [x] action_state_resource
  * `Cannot map a axislike input for action Move of kind Button`
- [x] axis_inputs
  * ```assertion `left == right` failed
  left: DualAxis
 right: Button```
- [x] default_controls
  * ```assertion `left == right` failed
  left: DualAxis
 right: Button```
- [x] input_processing
  * ```assertion `left == right` failed
  left: DualAxis
 right: Button```
- [ ] #612
  * I'm not sure here. The example runs but the rect does not move at all by pressing A/D/Left/Right...
- [x] twin_stick_controller
  * ```assertion `left == right` failed
  left: DualAxis
 right: Button```
- [x] virtual_dpad
  * ```assertion `left == right` failed
  left: DualAxis
 right: Button```

I was seeing the assertion crash on DualAxis/Button on the latest commit d32883661c72b4ff01be71ce65d9e9f2375d5f69  but then switched to v0.15 to try all the examples.

**Comment by alice-i-cecile** [comment]
Thanks for going through these! I'll get them cleaned up promptly.

**Comment by Ashe** [comment]
Yes this is a little confusing, before I could query `pressed` to see if input was essentially non-zero, and now i can only do that for buttons. Similarly, buttons now seem to be binary so I'm not quite sure how to make a gamepad trigger have a value - it seems it can only be bound as a button and not an axis? Is this no longer a feature?
