### ISSUE TITLE
How would I pass a mouse position through an input?

### ISSUE THREAD

**Issue by simbleau** [Leafwing-Studios/leafwing-input-manager#592]
I'm switching from natively serialized inputs to leafwing, and I realized that the `ActionLike` macro removes the ability to push data with your inputs.

Before I had something like this:

```rust
enum Inputs {
    MovingTo(x: 32, y: 32),
    MoveUp,
    MoveDown,
    ...
    Standing(dir: f32)
}
```

However, since `ActionLike` requires `Hash`, it greatly limits my ability to derive `ActionLike` on `Inputs`.

Specifically, in my game, imagine it's like League of Legends where you click on the screen, and that sends a `MovingTo(x, y)` input.

How does one accomplish this with Leafwing?

**Comment by alice-i-cecile** [comment]
You should call `ActionState::set_action_pair`, and store that information in the `ActionState` struct associated with your `MovingTo` variant :) This would be a good example though, so I'm going to leave this open.

**Comment by simbleau** [comment]
@alice-i-cecile  - This isn't seeming to work, or I'm doing something wrong...

```rust
pub struct PlayerInputPlugin;

impl Plugin for PlayerInputPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            PreUpdate,
            tap_to_move
                .run_if(in_state(GameState::InGame))
                .after(InputManagerSystem::ManualControl),
        );
    }
}

pub fn tap_to_move(
    windows: Query<&Window>,
    query_view: Query<(&Camera, &GlobalTransform), With<Camera2d>>,
    mouse: Res<ButtonInput<MouseButton>>,
    mut action_query: Query<&mut ActionState<PlayerMovementAction>, With<Predicted>>,
) {
    let window = windows.single();
    let (camera, view) = query_view.single();
    let Ok(mut action_state) = action_query.get_single_mut() else {
        return;
    };

    if let Some(world_position) = window
        .cursor_position()
        .and_then(|cursor| camera.viewport_to_world(view, cursor))
        .map(|ray| ray.origin.truncate())
    {
        if mouse.pressed(MouseButton::Left) {
            action_state.set_axis_pair(
                &PlayerMovementAction::Move,
                world_position.clamp(Vec2::NEG_ONE, Vec2::ONE),
            );
            info!("{:?}", world_position);
        }
    }
}
```

I am seeing the coordinates correctly to debug print, but it's not moving my player normally.

Furthermore, I only see `pair` and `update_pair` change... which is strange.
![Image](https://github.com/user-attachments/assets/002cd2e2-aade-4788-82c5-b439e90fabf6)


When I move with WASD, or another movement type, I see all three match. (example):
![Image](https://github.com/user-attachments/assets/96d5348f-818a-4079-9872-7468b5fc5aa2)

**Comment by simbleau** [comment]
I suspect it has something to do with the system sets or ordering...

There is only one example which does this, which I found here: https://github.com/Leafwing-Studios/leafwing-input-manager/blob/c2c80ee1b90a4767cc016d9c614cd4031abcfce0/examples/arpg_indirection.rs#L22-L25

**Comment by alice-i-cecile** [comment]
Generally this sort of logic should be in the `ManualControl` system set. Does that work for you?

**Comment by simbleau** [comment]
So, this is working on further investigation. The issue was somewhere in lightyear's automated input sending of leafwing inputs.
