### ISSUE TITLE
Crash for wasm/xbox controller (gilrs)

### ISSUE THREAD

**Issue by simbleau** [Leafwing-Studios/leafwing-input-manager#593]
## Version

0.14

## Operating system & version

MacOS, but compiled to WASM.

## What you did

Using leafwing for the first time and getting a crash from gilrs.

This crash happens as soon as I click a button with a leafwing input.

```
ERROR  Platform implementation error: got Connected event with id 1, when expected id 0 log.target = "gilrs::gamepad";log.module_path = "gilrs::gamepad";log.file = "/Users/simbleau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gilrs-0.10.9/src/gamepad.rs";log.line = 338;
nova_client-9d64afb0e4ef0d16.js:388 panicked at /Users/simbleau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gilrs-0.10.9/src/gamepad.rs:458:45:
called `Option::unwrap()` on a `None` value
```

<img width="990" alt="image" src="https://github.com/user-attachments/assets/f8777b87-fe3f-4076-9535-6e03a41f1ea9">

**Comment by alice-i-cecile** [comment]
I'm pretty sure this is a bug upstream in `gilrs` itself: I'm not sure what I could be doing differently there. Can you make an issue on their Gitlab and link it here please?

**Comment by simbleau** [comment]
https://gitlab.com/gilrs-project/gilrs/-/issues/169

**Comment by simbleau** [comment]
It is unblocked, appears fixed in the GitLab issue. @alice-i-cecile
