### ISSUE TITLE
Cannot find attribute `actionlike` in this scope

### ISSUE THREAD

**Issue by FlooferLand** [Leafwing-Studios/leafwing-input-manager#629]
## Version

0.15.0

## Operating system & version

Windows 11

## What you did

1. Made a new project using Bevy 0.14.2
2. Installed `leafwing-input-manager`

## What you expected to happen

The `actionlike` macro existing

## What actually happened

The `actionlike` macro doesn't exist

## Additional information

This was my code
```rs
use bevy::prelude::*;
use leafwing_input_manager::prelude::*;

#[derive(Actionlike, PartialEq, Eq, Hash, Clone, Copy, Debug, Reflect)]
pub enum GamePlayerAction {
    // Movement
    #[actionlike(DualAxis)] Walk,
    #[actionlike(DualAxis)] Look,
    #[actionlike(Axis)] Scroll,
    Jump,

    // Interaction
    InteractPrimary,
    InteractSecondary,
}
```

I've also tried importing in the procedural function manually installing `leafwing_input_manager_macros` to no avail.

**Comment by alice-i-cecile** [comment]
You're looking at the examples on main: they're too new! We should be releasing a new patch soon, sorry.
