### ISSUE TITLE
Merge the input method specific *Virtual* types into general Virtual* types

### ISSUE THREAD

**Issue by FlooferLand** [Leafwing-Studios/leafwing-input-manager#632]
_Made from https://github.com/Leafwing-Studios/leafwing-input-manager/discussions/631#discussioncomment-10674481_

## Which code could be improved?

[src/user_input/keyboard.rs](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/63ebdb21eab7f8c692bb40d6a610925c381919c4/src/user_input/keyboard.rs)

[src/user_input/mouse.rs](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/63ebdb21eab7f8c692bb40d6a610925c381919c4/src/user_input/mouse.rs)

[src/user_input/gamepad.rs](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/63ebdb21eab7f8c692bb40d6a610925c381919c4/src/user_input/gamepad.rs)

## How should this be changed?

Having several types for each input method doesn't make much sense here and tends to clutter things.
For example, there is no `MouseVirtualAxis` type right now because it wasn't taken into count, even though I believe the mouse buttons implement `Buttonlike`.

These ~6 structs could be merged into 3 simpler types: `VirtualAxis` `VirtualDPad`, `VirtualDPad3d`
The implementation would probably use generics and `Buttonlike`

**Comment by alice-i-cecile** [comment]
@FlooferLand FYI, the reason why you were getting the "KeyCode does not implement Buttonlike" error is because of the various feature flags: https://github.com/Leafwing-Studios/leafwing-input-manager/blob/63ebdb21eab7f8c692bb40d6a610925c381919c4/Cargo.toml#L20

Feel free to open a draft PR and ask for help from myself and the community there :)

**Comment by Shute052** [comment]
- This PR #623 might be what you're looking for

**Comment by FlooferLand** [comment]
> * This PR [Make virtual axial controls more flexible, accepting any kind of `Buttonlike` #623](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/623) might be what you're looking for

Yes! Exactly what i was looking for.
I will close this now, hopefully that PR gets merged.
