### ISSUE TITLE
KeyboardVirtualDPad doc comment is wrong (?)

### ISSUE THREAD

**Issue by AnAverageGitUser** [Leafwing-Studios/leafwing-input-manager#633]
## What problem did the developer encounter?

The description of "KeyboardVirtualDPad" is in part wrong or I did not understand some concept here yet, in which case you can ignore and close this.
The description of "KeyboardVirtualDPad" says: "A virtual single-axis control constructed from four KeyCodes." which is the same as what "KeyboardVirtualAxis" says. However in my understanding "KeyboardVirtualDPad" is intended for two axis and not one. This might be a copy paste error.

## How could this be better documented?

Instead of 
"A virtual **single**-axis control constructed from four KeyCodes."
it should probably say
"A virtual **dual**-axis control constructed from four KeyCodes."

In any case: thank you for pouring your time into this!

**Comment by alice-i-cecile** [comment]
I'm planning to merge that PR as soon as 0.15.1 is cut; closing as resolved.
