### ISSUE TITLE
CI to build wasm

### ISSUE THREAD

**Issue by gak** [Leafwing-Studios/leafwing-input-manager#636]
## What could be improved?

It would catch small Wasm build problems like #590

## How should this be changed?

Just a new entry in https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/.github/workflows/ci.yml maybe called  `check-wasm` or make the whole thing run with a matrix of linux and wasm i.e. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

**Comment by gak** [comment]
Can do this if you haven't already done it @alice-i-cecile 😄

**Comment by alice-i-cecile** [comment]
Yes please!
