### ISSUE TITLE
`get_pressed()` panic when at least one axis or axispair is set

### ISSUE THREAD

**Issue by AndreasHGK** [Leafwing-Studios/leafwing-input-manager#638]
## Version

0.15.0

## Operating system & version

Nixos, linux 6.6.52

## What you did

The lightyear library uses `ActionState::get_pressed()` to display some info, which leads to a panic when at least one AxisPair or Axis input has a value set. (https://github.com/cBournhonesque/lightyear/issues/655)

## What you expected to happen

I expect `get_pressed` to ignore all non pressable (axis, axispair) inputs rather than panic.

## What actually happened

The following panic occurred:
```
thread 'Compute Task Pool (11)' panicked at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:737:9:
assertion `left == right` failed
  left: DualAxis
 right: Button
```
(full stack trace can be seen in the issue linked above)

## Additional information

The following test reproduces this:
```rs
#[test]
fn test() {
    use bevy::reflect::Reflect;
    use leafwing_input_manager::{Actionlike, InputControlKind};

    #[derive(Reflect, Clone, PartialEq, Eq, Hash, Debug)]
    enum PlayerInput {
        Run,
        Jump,
        Shoot,
        CameraPan,
    }

    impl Actionlike for PlayerInput {
        fn input_control_kind(&self) -> InputControlKind {
            match self {
                Self::Run => InputControlKind::DualAxis,
                Self::Jump => InputControlKind::Button,
                Self::Shoot => InputControlKind::Button,
                Self::CameraPan => InputControlKind::DualAxis,
            }
        }
    }

    let mut state = ActionState::<PlayerInput>::default();
    state.set_axis_pair(&PlayerInput::Run, Vec2::ZERO);
    assert_eq!(state.get_pressed().len(), 0);
}
```

**Comment by stinkytoe** [comment]
This is definitely a regression in v0.15, fwiw.

Using the twin_stick_controller example as my test unit, I get the expected behavior of seeing my game pad axis sticks report events on both tag v0.14.0 , and on main (branch 36441c71a8f73e978b05f27b33e735ec14a07bf4 specifically). On v0.15, or when I reproduce similar code in my project (linked to v0.15 in my Cargo.toml), I get the same panic that @AndreasHGK is reporting.

**Comment by alice-i-cecile** [comment]
Can you reproduce this on main? I believe this should be fixed now.

**Comment by stinkytoe** [comment]
Yes, works on 36441c71a8f73e978b05f27b33e735ec14a07bf4, which is where main is currently pointing. Is the recommendation to use main until next release?

**Comment by alice-i-cecile** [comment]
Yes, but I'm aiming to do a point release in the next couple of days :)
