### ISSUE TITLE
Missing autocomplete and documentation for `ActionState` functions

### ISSUE THREAD

**Issue by realStandal** [Leafwing-Studios/leafwing-input-manager#65]
## Version

0.1.2

## Operating system & version

Windows 10

## What you did

Setup the minimal example and began modifying the provided system.

## What you expected to happen

When I use the [methods](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/db6178f0b30d29ed98936b7175f7c6544a0e95a7/src/action_state.rs#L36) of the `ActionState`, I should see suggestions and documentation for each method - provided as I type.

## What actually happened

I do not see suggestions, such as "Was the button released since the last time [`ActionState::update`] was called?" for `ActionState.just_pressed()`.

## Additional Details

My app compiles and executes as expected - the message "I'm jumping!" displays once the appropriate key is pressed.

**Comment by alice-i-cecile** [comment]
Hmm. I'm very unsure how to start going about fixing / reproducing this.

Which IDE and language-relevant extensions?

**Comment by realStandal** [comment]
@alice-i-cecile Apologies, I made horrid assumptions and don't think my brain was on when I wrote this:

- VS Code 1.64.0
- [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) v0.2.932

**Comment by alice-i-cecile** [comment]
![image](https://user-images.githubusercontent.com/3579909/153099721-fcc1973b-295b-4ff3-8f07-51024e22223a.png)

- rustc: 1.58.1
- VS Code: 1.63.2
- rust-analyzer: v0.2.867

Works on my machine, on an older version. Maybe I fixed it in on the `dev` branch somehow? Or check your RA autocomplete features: I have all of them enabled.

I don't think there's anything to be done on my end, sorry.

**Comment by realStandal** [comment]
Thank you for the settings tip, did the trick :)
