### ISSUE TITLE
Handle one-dimensional analogue input

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#78]
Define threshold partitioning.

Use #76 to get the value.

Simpler version of #50.

**Comment by alterae** [comment]
idk if this is helpful but the way Godot does it is that every action is a floating-point value, and buttons simply set their corresponding actions to zero or one, while analog inputs set the actions to anywhere from zero to one. the normal `pressed`, `just_pressed`, etc. apis are still present (with "pressed" being anything over a configurable threshold that defaults to zero), but you can also get the raw analog value with `get_action_strength`, which is useful for movement controls and the like

**Comment by johanhelsing** [comment]
For what it's worth, the single float approach is also what `bevy_input_actionmap` does: https://github.com/lightsoutgames/bevy_input_actionmap/blob/84c19d027bda2ec38a1f47591a8513af763bb572/src/lib.rs#L322

**Comment by alice-i-cecile** [comment]
Completed.
