### ISSUE TITLE
Actions which are dataful enum variants such as `Move(Direction)` aren't fully emitted

### ISSUE THREAD

**Issue by ChristianIvicevic** [Leafwing-Studios/leafwing-input-manager#81]
## Version

0.2.0

## Operating system & version

macOS (should be irrelevant)

## What you did

```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum Direction {
    North = 0,
    NorthEast,
    East,
    SouthEast,
    South,
    SouthWest,
    West,
    NorthWest,
}

/// Actions that can be performed based on input.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Actionlike, Hash)]
pub(crate) enum InputAction {
    Move(Direction),
}

/// Bundle containing a set of all components and bundles associated with a player.
#[derive(Bundle)]
struct PlayerBundle {
    player: Player,
    #[bundle]
    input_manager: InputManagerBundle<InputAction>,
}

impl Default for PlayerBundle {
    fn default() -> Self {
        let mut input_map = InputMap::default();

        input_map.insert(InputAction::Move(Direction::North), KeyCode::W);
        input_map.insert(InputAction::Move(Direction::South), KeyCode::S);
        input_map.insert(InputAction::Move(Direction::West), KeyCode::A);
        input_map.insert(InputAction::Move(Direction::East), KeyCode::D);
        input_map.insert(InputAction::Attack, KeyCode::Q);

        Self {
            player: Player,
            input_manager: InputManagerBundle {
                input_map,
                action_state: ActionState::default(),
            },
        }
    }
}
```

You see that I am binding the four keys WASD to the different direction, however only the first action is emitted when I press W and not the other actions.

## What you expected to happen

I'd expect that S, A and D work and emit the correct action.

## What actually happened

Only W works.

**Comment by alice-i-cecile** [comment]
So, thinking about this further: this is due to the way that the `Actionlike` enum ends up getting numbered, both with `strum` and the new handwritten derive.

Each of the top-level variants gets a number, but the inner variants don't. Effectively, what we want instead is a numbering over the leaf nodes of our enum tree, and walk the enum tree with a depth-first search.

**Comment by alice-i-cecile** [comment]
This is a special case of #60, but should be dramatically more tractable to solve.
